.\" The first line sets the Title (INVISICALC), section (1), Date, Source (e.g., GNOME), and Manual section (User Commands)
.TH INVISICALC 1 "January 03, 2026" "GNOME" "User Commands"

.\" NAME section: The command name followed by a one-line description
.SH NAME
invisicalc \- a simple calculator for the GNOME desktop

.\" SYNOPSIS section: Describes the formal syntax for running the command
.SH SYNOPSIS
.B invisicalc
[
.I options
]
[
.I file
]...

.\" DESCRIPTION section: A full explanation of the program's functionality
.SH DESCRIPTION
.B invisicalc
is a user-friendly calculator application built with GTK4 and Libadwaita. It provides basic arithmetic functions in a clean, integrated interface within the GNOME desktop environment.

.\" OPTIONS section: Lists and explains command-line arguments
.SH OPTIONS

.TP
.B \-\-version
Display the application version and exit.

.TP
.B \-h, \-\-help
Show the standard GTK help options.

.\" EXAMPLES section: How to use the program in practice
.SH EXAMPLES
.B invisicalc
&

.br
Launch the calculator in the background.

.\" SEE ALSO section: A comma-separated list of related man pages
.SH "SEE ALSO"
gnome-calculator(1), gtk4(7), libadwaita(1)

.\" BUGS section: A place to list known issues or reporting information
.SH BUGS
Report bugs to the issue tracker at <https://github.com/jordanblakey/invisicalc/issues>.

.\" AUTHOR section: Optional, contains author information
.SH AUTHOR
Jordan Blakey <jordan.t.blakey@gmail.com>
